### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by abulte** [koumoul-dev/udata-data-fair#1]
Hi,

We're about to release udata2 that will be compatible with python > 3.7 only https://github.com/opendatateam/udata/pull/1766. If you want this extension to be enabled when data.gouv.fr switches to udata2, you'll need to make it compatible with python3.7. This should not be a huge effort.

**Comment by albanm** [comment]
Hello,

I released version 0.3.1 that should be compatible with python 3. I simply used 2to3 on the py code.

Unfortunately I didn't really test. We use the udata docker image, but the last versions published do not contain python3.7 so they are not compatible with gouvfr theme and therefore fail.

**Comment by abulte** [comment]
I just merged of version of https://github.com/opendatateam/udata-dockers on `master` that should be fully python-3.7 compatible.

**Comment by nicolas-bonnel** [comment]
Thanks, can you tell us when this reach production on data.gouv.fr so that we can close this ticket ?

**Comment by abulte** [comment]
The python3 version of data.gouv.fr is in production since 2020-03-16.

I just released the 0.3.1 version of your plugin on https://demo.data.gouv.fr/. Can you tell us if it works? It it doesn't, can you test locally and keep us posted?

Thanks.

**Comment by nicolas-bonnel** [comment]
This does not work on https://demo.data.gouv.fr/. Tested on this page : https://demo.data.gouv.fr/fr/datasets/les-aides-financieres-de-lademe-1/#_

We will test locally with the new version of udata-docker

**Comment by nicolas-bonnel** [comment]
Is the plugin activated on data.gouv.fr ?

It is working on our staging environment with the last version for udata : https://udata.staging-koumoul.com/fr/datasets/sitadel-morbihan-3/

**Comment by abulte** [comment]
The plugin was installed but not enabled on demo.data.gouv.fr :-/ sorry for that. Looks good for me https://demo.data.gouv.fr/fr/datasets/les-aides-financieres-de-lademe-1/#_, ok for you?

**Comment by nicolas-bonnel** [comment]
Yes, it looks good :+1:

**Comment by abulte** [comment]
Deployed on prod https://www.data.gouv.fr/fr/datasets/les-aides-financieres-de-lademe-1/#
